name: Module release

on:
  push:
    branches:
      - main

# on:
#   - pull_request

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - name: Get matrix
        id: get-matrix
        uses: hellofresh/action-changed-files@v3
        with:
          pattern: modules/(?P<module>[^/]+)
  release-module:
    needs: generate-matrix
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix).include[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd modules/${{ matrix.module }}
          python3 "${GITHUB_WORKSPACE}"/scripts/prep_module.py
          npm install
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     cd modules/${{ matrix.module }} && ls  -la
      #     cat package.json
      #     npx semantic-release -t ${{ matrix.module }}/'${version}'

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Create Artifact
        run: |
          module_name=${{ matrix.module }}
          artifact_dir="dist/${{ matrix.module }}"

          mkdir -p $artifact_dir
          cp -R $module_name/* $artifact_dir/

          zip -r release_artifact.zip $artifact_dir
        working-directory: modules

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: release_artifact
          path: release_artifact.zip
